[project]
name = "phk-kg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.5.4",
    "odfpy>=1.4.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "xlrd>=2.0.2",
]
